# Site settings
title: blog
email: gazhenko.jemmy@gatech.edu
description: > # this means to ignore newlines until "baseurl:"
    by jemmy gazhenko. a place where I keep my thought about tech, programming, devops, and other random stuff.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: jgazhenko
github_username:  gazhenko

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  woodworking:
    output: true
    permalink: /woodworking/:path/
  life:
    output: true
    permalink: /life/:path/

plugins:
  - jekyll-paginate
